version: '3.5'
services:
  service-a:
    build:
      context: service-a
      dockerfile: Dockerfile
      network: example-network
    ports:
      - "8000:8000"
  service-b:
    build:
      context: service-b
      dockerfile: Dockerfile
      network: example-network
    ports:
      - "8001:8001"

networks:
  example-network:
    name: example-network
    driver: bridge