version: '3.5'
services:
  service-a:
    build:
      context: service-a
      dockerfile: Dockerfile
    networks: 
      - example-network
    ports:
      - "8000:8080"
    environment:
      - DB=http://service-b:8081
  service-b:
    build:
      context: service-b
      dockerfile: Dockerfile
    networks: 
      - example-network

networks:
  example-network:
    name: example-network
    driver: bridge